spring.application.name=testSpring
spring.datasource.url=jdbc:mysql://localhost:3306/springboottest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8090
server.servlet.context-path=/testSpring


